module.exports = {
  Form: require('./Form'),
  Submission: require('./Submission'),
  Website: require('./Website'),
  QRCode: require('./QRCode'),
  ChatWidget: require('./ChatWidget'),
  Store: require('./store/Store'),
  StoreTemplate: require('./store/StoreTemplate'),
  StorePage: require('./store/StorePage'),
  StoreProduct: require('./store/StoreProduct'),
  StoreCollection: require('./store/StoreCollection'),
  StoreTestimonial: require('./store/StoreTestimonial'),
  StoreCustomer: require('./store/StoreCustomer'),
  StoreOrder: require('./store/StoreOrder'),
  StoreDiscount: require('./store/StoreDiscount'),
  StoreShipping: require('./store/StoreShipping'),
  StorePayment: require('./store/StorePayment'),
  StoreEmailSettings: require('./store/StoreEmailSettings'),
  StoreVisit: require('./store/StoreVisit'),
  SeoProject: require('./seo/SeoProject'),
  SeoAudit: require('./seo/SeoAudit'),
  SeoIssue: require('./seo/SeoIssue'),
  SeoKeyword: require('./seo/SeoKeyword'),
  SeoCompetitor: require('./seo/SeoCompetitor'),
  SeoStrategy: require('./seo/SeoStrategy'),
  SeoContent: require('./seo/SeoContent'),
  SeoHistory: require('./seo/SeoHistory'),
};