module.exports = {
  Form: require('./Form'),
  Submission: require('./Submission'),
  Website: require('./Website'),
  QRCode: require('./QRCode'),
  ChatWidget: require('./ChatWidget'),
  Store: require('./store/Store'),
  StoreTemplate: require('./store/StoreTemplate'),
  StorePage: require('./store/StorePage'),
  StoreProduct: require('./store/StoreProduct'),
  StoreCollection: require('./store/StoreCollection'),
  StoreCustomer: require('./store/StoreCustomer'),
  StoreOrder: require('./store/StoreOrder'),
  StoreDiscount: require('./store/StoreDiscount'),
  StoreShipping: require('./store/StoreShipping'),
  StorePayment: require('./store/StorePayment'),
  StoreEmailSettings: require('./store/StoreEmailSettings'),
};